_target_: parallel_wavegan.models.ParallelWaveGANDiscriminator
in_channels: 1
out_channels: 1
kernel_size: 3
layers: 3
conv_channels: 64
dilation_factor: 1
nonlinear_activation: LeakyReLU
nonlinear_activation_params:
  negative_slope: 0.2
bias: True
use_weight_norm: True